plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/work/.openclaw/workspace/zamgrow-exchange/frontend/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/home/work/.openclaw/workspace/zamgrow-exchange/frontend"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]