import { Listing } from '../store/slices/listingsSlice'
import { User } from '../store/slices/authSlice'
import { PriceDataPoint, HeatmapData } from '../store/slices/marketSlice'
import { Notification } from '../store/slices/notificationsSlice'

export const PROVINCES = [
  { id: 1, name: 'Central', capital: 'Kabwe', districts: ['Mkushi', 'Serenje', 'Mumbwa', 'Chibombo', 'Kapiri Mposhi'] },
  { id: 2, name: 'Copperbelt', capital: 'Ndola', districts: ['Kitwe', 'Chingola', 'Mufulira', 'Kalulushi', 'Lufwanyama'] },
  { id: 3, name: 'Eastern', capital: 'Chipata', districts: ['Petauke', 'Katete', 'Lundazi', 'Chadiza', 'Mambwe'] },
  { id: 4, name: 'Luapula', capital: 'Mansa', districts: ['Nchelenge', 'Kawambwa', 'Mwense', 'Samfya'] },
  { id: 5, name: 'Lusaka', capital: 'Lusaka', districts: ['Chongwe', 'Kafue', 'Chilanga', 'Luangwa'] },
  { id: 6, name: 'Muchinga', capital: 'Chinsali', districts: ['Mpika', 'Nakonde', 'Isoka', 'Shiwangandu'] },
  { id: 7, name: 'Northern', capital: 'Kasama', districts: ['Mbala', 'Luwingu', 'Mporokoso', 'Chilubi'] },
  { id: 8, name: 'North-Western', capital: 'Solwezi', districts: ['Mwinilunga', 'Zambezi', 'Kabompo', 'Chavuma'] },
  { id: 9, name: 'Southern', capital: 'Choma', districts: ['Mazabuka', 'Monze', 'Kalomo', 'Gwembe', 'Pemba'] },
  { id: 10, name: 'Western', capital: 'Mongu', districts: ['Senanga', 'Sesheke', 'Kaoma', 'Kalabo'] },
]

export const CATEGORIES = [
  { id: 1, name: 'Cereals', emoji: '🌾', items: ['Maize', 'Wheat', 'Sorghum', 'Millet'] },
  { id: 2, name: 'Legumes', emoji: '🫘', items: ['Soya Beans', 'Groundnuts', 'Beans', 'Cowpeas'] },
  { id: 3, name: 'Vegetables', emoji: '🥬', items: ['Tomatoes', 'Cabbage', 'Onions', 'Rape', 'Okra'] },
  { id: 4, name: 'Fruits', emoji: '🍊', items: ['Mangoes', 'Bananas', 'Avocados', 'Pineapples'] },
  { id: 5, name: 'Livestock', emoji: '🐄', items: ['Cattle', 'Goats', 'Sheep', 'Pigs'] },
  { id: 6, name: 'Fisheries', emoji: '🐟', items: ['Kapenta', 'Tilapia', 'Bream', 'Catfish'] },
  { id: 7, name: 'Dairy', emoji: '🥛', items: ['Fresh Milk', 'Yoghurt', 'Cheese'] },
  { id: 8, name: 'Poultry', emoji: '🐔', items: ['Broilers', 'Layers', 'Eggs', 'Day-old Chicks'] },
  { id: 9, name: 'Root Crops', emoji: '🍠', items: ['Cassava', 'Sweet Potatoes', 'Irish Potatoes'] },
  { id: 10, name: 'Cash Crops', emoji: '🌿', items: ['Tobacco', 'Cotton', 'Sunflower', 'Coffee'] },
]

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'John Banda',
    phone: '+260971234567',
    email: 'john@example.com',
    role: 'farmer',
    province: 'Central',
    district: 'Mkushi',
    credits: 150,
    subscription: 'pro',
    verified: true,
    rating: 4.8,
    totalReviews: 23,
    createdAt: '2023-06-15T08:00:00Z',
  },
  {
    id: 'u2',
    name: 'Grace Mwale',
    phone: '+260962345678',
    email: 'grace@agrobuy.zm',
    role: 'buyer',
    province: 'Lusaka',
    district: 'Chilanga',
    credits: 500,
    subscription: 'premium',
    verified: true,
    rating: 4.9,
    totalReviews: 45,
    createdAt: '2023-03-10T08:00:00Z',
  },
  {
    id: 'u3',
    name: 'Patrick Mulenga',
    phone: '+260953456789',
    role: 'dealer',
    province: 'Copperbelt',
    district: 'Kitwe',
    credits: 300,
    subscription: 'basic',
    verified: true,
    rating: 4.5,
    totalReviews: 12,
    createdAt: '2023-08-20T08:00:00Z',
  },
  {
    id: 'u4',
    name: 'Admin User',
    phone: '+260964567890',
    email: 'admin@zamgrow.zm',
    role: 'admin',
    province: 'Lusaka',
    district: 'Lusaka',
    credits: 9999,
    subscription: 'premium',
    verified: true,
    rating: 5.0,
    totalReviews: 0,
    createdAt: '2023-01-01T08:00:00Z',
  },
  {
    id: 'u5',
    name: 'Mary Phiri',
    phone: '+260975678901',
    role: 'farmer',
    province: 'Eastern',
    district: 'Petauke',
    credits: 50,
    subscription: 'free',
    verified: false,
    rating: 4.2,
    totalReviews: 6,
    createdAt: '2023-11-05T08:00:00Z',
  },
]

const LISTING_PHOTOS: Record<string, string[]> = {
  Maize: [
    'https://images.unsplash.com/photo-1601593346740-925612772716?w=800',
    'https://images.unsplash.com/photo-1589923188900-85dae523342b?w=800',
  ],
  'Soya Beans': [
    'https://images.unsplash.com/photo-1612257999641-5ba09d1c9b12?w=800',
  ],
  Tomatoes: [
    'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=800',
    'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=800',
  ],
  Cattle: [
    'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800',
  ],
  Cabbage: [
    'https://images.unsplash.com/photo-1557844352-761f2565b576?w=800',
  ],
  Groundnuts: [
    'https://images.unsplash.com/photo-1567364840671-95b84be9c4ae?w=800',
  ],
  default: [
    'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800',
  ],
}

function getPhotos(product: string): string[] {
  return LISTING_PHOTOS[product] || LISTING_PHOTOS.default
}

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'l1',
    title: '50 Bags of Maize (50kg each) - Premium Grade',
    description: 'Fresh maize harvested from my 20-hectare farm in Mkushi. Properly dried to 12.5% moisture content. FRA-certified quality. Ready for immediate collection. Bulk discount available for orders above 100 bags.',
    type: 'sell',
    price: 180,
    unit: 'bag (50kg)',
    quantity: 50,
    category: 'Cereals',
    product: 'Maize',
    province: 'Central',
    district: 'Mkushi',
    photos: getPhotos('Maize'),
    sellerId: 'u1',
    sellerName: 'John Banda',
    sellerRating: 4.8,
    sellerPhone: '+260971234567',
    verified: true,
    status: 'active',
    views: 234,
    offers: 5,
    createdAt: '2024-01-15T08:00:00Z',
    expiresAt: '2024-04-15T08:00:00Z',
    isFeatured: true,
  },
  {
    id: 'l2',
    title: 'Wanted: Soya Beans - 200 Metric Tonnes',
    description: 'We are a registered processing company in Chilanga looking to purchase soya beans in bulk. Minimum 200MT. We offer competitive prices and prompt payment via mobile money or bank transfer. Preference for Eastern and Central provinces.',
    type: 'buy',
    price: 3200,
    unit: 'metric tonne',
    quantity: 200,
    category: 'Legumes',
    product: 'Soya Beans',
    province: 'Lusaka',
    district: 'Chilanga',
    photos: getPhotos('Soya Beans'),
    sellerId: 'u2',
    sellerName: 'Grace Mwale',
    sellerRating: 4.9,
    sellerPhone: '+260962345678',
    verified: true,
    status: 'active',
    views: 456,
    offers: 12,
    createdAt: '2024-01-18T08:00:00Z',
    expiresAt: '2024-04-18T08:00:00Z',
    isFeatured: true,
  },
  {
    id: 'l3',
    title: 'Fresh Tomatoes - 500 Crates Available',
    description: 'Grade A tomatoes from our greenhouse farm in Mazabuka. Varieties: Rodade and Heinz. Available from Monday to Saturday. Delivery to Lusaka markets possible for orders above 50 crates.',
    type: 'sell',
    price: 85,
    unit: 'crate (20kg)',
    quantity: 500,
    category: 'Vegetables',
    product: 'Tomatoes',
    province: 'Southern',
    district: 'Mazabuka',
    photos: getPhotos('Tomatoes'),
    sellerId: 'u3',
    sellerName: 'Patrick Mulenga',
    sellerRating: 4.5,
    sellerPhone: '+260953456789',
    verified: true,
    status: 'active',
    views: 189,
    offers: 3,
    createdAt: '2024-01-20T08:00:00Z',
    expiresAt: '2024-02-20T08:00:00Z',
    isFeatured: false,
  },
  {
    id: 'l4',
    title: 'Grade A Groundnuts - 20 Tonnes Available',
    description: 'Shell-on groundnuts from Petauke district. Good germination rate 95%+. Can also supply shelled. Lorry transport can be arranged to major towns.',
    type: 'sell',
    price: 4500,
    unit: 'metric tonne',
    quantity: 20,
    category: 'Legumes',
    product: 'Groundnuts',
    province: 'Eastern',
    district: 'Petauke',
    photos: getPhotos('Groundnuts'),
    sellerId: 'u5',
    sellerName: 'Mary Phiri',
    sellerRating: 4.2,
    sellerPhone: '+260975678901',
    verified: false,
    status: 'active',
    views: 98,
    offers: 2,
    createdAt: '2024-01-22T08:00:00Z',
    expiresAt: '2024-04-22T08:00:00Z',
    isFeatured: false,
  },
  {
    id: 'l5',
    title: 'Beef Cattle - 25 Heads for Sale',
    description: 'Mature Brahman cross cattle, average weight 350-400kg. All vaccinated and certified disease-free. Located in Choma. Serious buyers only.',
    type: 'sell',
    price: 8500,
    unit: 'head',
    quantity: 25,
    category: 'Livestock',
    product: 'Cattle',
    province: 'Southern',
    district: 'Choma',
    photos: getPhotos('Cattle'),
    sellerId: 'u1',
    sellerName: 'John Banda',
    sellerRating: 4.8,
    sellerPhone: '+260971234567',
    verified: true,
    status: 'active',
    views: 312,
    offers: 7,
    createdAt: '2024-01-10T08:00:00Z',
    expiresAt: '2024-04-10T08:00:00Z',
    isFeatured: true,
  },
  {
    id: 'l6',
    title: 'Cabbage - 1000 Heads Ready Now',
    description: 'Copenhagen Market variety. Each head weighs 1.5-2.5kg. Farm gate collection or delivery to Kitwe market. Weekly supply available.',
    type: 'sell',
    price: 8,
    unit: 'head',
    quantity: 1000,
    category: 'Vegetables',
    product: 'Cabbage',
    province: 'Copperbelt',
    district: 'Kitwe',
    photos: getPhotos('Cabbage'),
    sellerId: 'u3',
    sellerName: 'Patrick Mulenga',
    sellerRating: 4.5,
    sellerPhone: '+260953456789',
    verified: true,
    status: 'active',
    views: 145,
    offers: 4,
    createdAt: '2024-01-25T08:00:00Z',
    expiresAt: '2024-03-25T08:00:00Z',
    isFeatured: false,
  },
  {
    id: 'l7',
    title: 'Looking to Buy: Maize 100+ Bags Weekly',
    description: 'We run a school feeding program in Lusaka and need consistent maize supply. Looking for reliable farmers who can supply 100+ bags per week throughout the year. Good prices offered, payment within 24 hours.',
    type: 'buy',
    price: 185,
    unit: 'bag (50kg)',
    quantity: 500,
    category: 'Cereals',
    product: 'Maize',
    province: 'Lusaka',
    district: 'Lusaka',
    photos: getPhotos('Maize'),
    sellerId: 'u2',
    sellerName: 'Grace Mwale',
    sellerRating: 4.9,
    sellerPhone: '+260962345678',
    verified: true,
    status: 'active',
    views: 567,
    offers: 18,
    createdAt: '2024-01-12T08:00:00Z',
    expiresAt: '2024-07-12T08:00:00Z',
    isFeatured: true,
  },
  {
    id: 'l8',
    title: 'Wheat Grain - 30 Tonnes from Choma',
    description: 'Hard red wheat, protein content 12-14%. Suitable for milling. Tested and certified. Transport available to Lusaka flour mills.',
    type: 'sell',
    price: 5200,
    unit: 'metric tonne',
    quantity: 30,
    category: 'Cereals',
    product: 'Wheat',
    province: 'Southern',
    district: 'Choma',
    photos: getPhotos('default'),
    sellerId: 'u5',
    sellerName: 'Mary Phiri',
    sellerRating: 4.2,
    sellerPhone: '+260975678901',
    verified: false,
    status: 'active',
    views: 78,
    offers: 1,
    createdAt: '2024-01-28T08:00:00Z',
    expiresAt: '2024-04-28T08:00:00Z',
    isFeatured: false,
  },
]

// Generate price history for last 6 months
function generatePriceHistory(product: string, basePrice: number, province: string): PriceDataPoint[] {
  const data: PriceDataPoint[] = []
  const now = new Date()
  for (let i = 180; i >= 0; i -= 7) {
    const date = new Date(now)
    date.setDate(date.getDate() - i)
    const variation = (Math.random() - 0.5) * 0.15 * basePrice
    const seasonal = Math.sin((i / 180) * Math.PI) * 0.1 * basePrice
    data.push({
      date: date.toISOString().split('T')[0],
      price: Math.round(basePrice + variation + seasonal),
      volume: Math.round(50 + Math.random() * 200),
      province,
    })
  }
  return data
}

export const MOCK_PRICE_DATA: Record<string, PriceDataPoint[]> = {
  Maize: generatePriceHistory('Maize', 180, 'all'),
  'Soya Beans': generatePriceHistory('Soya Beans', 3200, 'all'),
  Wheat: generatePriceHistory('Wheat', 5200, 'all'),
  Groundnuts: generatePriceHistory('Groundnuts', 4500, 'all'),
  Tomatoes: generatePriceHistory('Tomatoes', 85, 'all'),
}

export const MOCK_HEATMAP_DATA: HeatmapData[] = [
  { province: 'Central', provinceId: 1, avgPrice: 175, totalListings: 45, priceChange: 2.5 },
  { province: 'Copperbelt', provinceId: 2, avgPrice: 195, totalListings: 38, priceChange: -1.2 },
  { province: 'Eastern', provinceId: 3, avgPrice: 165, totalListings: 62, priceChange: 5.3 },
  { province: 'Luapula', provinceId: 4, avgPrice: 190, totalListings: 21, priceChange: 0.8 },
  { province: 'Lusaka', provinceId: 5, avgPrice: 205, totalListings: 87, priceChange: 3.1 },
  { province: 'Muchinga', provinceId: 6, avgPrice: 170, totalListings: 18, priceChange: -0.5 },
  { province: 'Northern', provinceId: 7, avgPrice: 180, totalListings: 29, priceChange: 1.9 },
  { province: 'North-Western', provinceId: 8, avgPrice: 200, totalListings: 15, priceChange: 4.2 },
  { province: 'Southern', provinceId: 9, avgPrice: 168, totalListings: 54, priceChange: 2.7 },
  { province: 'Western', provinceId: 10, avgPrice: 185, totalListings: 23, priceChange: -2.1 },
]

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: 'offer',
    title: 'New Offer Received',
    message: 'Grace Mwale made an offer of ZMW 170/bag on your Maize listing',
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    linkTo: '/listings/l1',
  },
  {
    id: 'n2',
    type: 'price_alert',
    title: 'Price Alert: Soya Beans',
    message: 'Soya Beans prices in Eastern province rose by 5.3% this week',
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    linkTo: '/market',
  },
  {
    id: 'n3',
    type: 'system',
    title: 'Listing Approved',
    message: 'Your listing "50 Bags of Maize" has been approved and is now live',
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    linkTo: '/listings/l1',
  },
  {
    id: 'n4',
    type: 'payment',
    title: 'Credits Added',
    message: 'ZMW 100 credits added to your account via MTN Mobile Money',
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
]

export const MOCK_PRICE_SUGGESTIONS: Record<string, { min: number; avg: number; max: number; confidence: number; trend: string }> = {
  Maize: { min: 155, avg: 178, max: 205, confidence: 87, trend: 'up' },
  'Soya Beans': { min: 2800, avg: 3150, max: 3600, confidence: 82, trend: 'up' },
  Wheat: { min: 4800, avg: 5200, max: 5700, confidence: 79, trend: 'stable' },
  Groundnuts: { min: 4000, avg: 4500, max: 5200, confidence: 75, trend: 'down' },
  Tomatoes: { min: 70, avg: 88, max: 120, confidence: 65, trend: 'up' },
  Cattle: { min: 7500, avg: 8500, max: 10000, confidence: 71, trend: 'stable' },
  Cabbage: { min: 6, avg: 9, max: 14, confidence: 68, trend: 'down' },
}

export const SUBSCRIPTION_PLANS = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    credits: 10,
    features: [
      '10 credits/month',
      '2 active listings',
      'Basic market prices',
      'Email support',
    ],
    color: 'gray',
    popular: false,
  },
  {
    id: 'basic',
    name: 'Basic',
    price: 99,
    credits: 50,
    features: [
      '50 credits/month',
      '10 active listings',
      'Real-time market prices',
      'AI price suggestions',
      'Priority support',
    ],
    color: 'blue',
    popular: false,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 249,
    credits: 150,
    features: [
      '150 credits/month',
      'Unlimited listings',
      'Advanced market analytics',
      'AI price suggestions',
      'Featured listings (3/month)',
      'SMS notifications',
      'Dedicated support',
    ],
    color: 'green',
    popular: true,
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 599,
    credits: 500,
    features: [
      '500 credits/month',
      'Unlimited listings',
      'Full market intelligence',
      'Bulk trade tools',
      'Unlimited featured listings',
      'API access',
      'Account manager',
      'Custom reports',
    ],
    color: 'amber',
    popular: false,
  },
]
